# https://dependabot.com/docs/config-file/

version: 1
update_configs:
- package_manager: "go:modules"
  directory: "/"
  update_schedule: "weekly"
  default_reviewers:
  - airbe
  - bdronneau
  - ViBiOh
